free5gc/smf

service/init.go
Fix the issue https://github.com/free5gc/free5gc/issues/117.
=> Fix character corruption in Send PFCP Association Request log

context/ue_datapath.go
DestinationIP: 60.60.0.200 only one UPF
```
info:
version: 1.0.0
description: Routing information for UE
ueRoutingInfo:
- SUPI: imsi-2089300007487
AN: 10.200.200.101
PathList:
- DestinationIP: 60.60.0.101
UPF: !!seq
- BranchingUPF
- AnchorUPF1
- DestinationIP: 60.60.0.103
UPF: !!seq
- BranchingUPF
- AnchorUPF2
- DestinationIP: 60.60.0.200
UPF: !!seq
- AnchorUPF1
```
```
Activated: false
IsDefault Path: false
Has Braching Point: false
Destination IP: 60.60.0.103
Destination Port: 
DataPath Routing Information
1th Node in the Path
Current UPF IP: 10.200.200.102
Previous UPF IP: None
Next UPF IP: 10.200.200.103
2th Node in the Path
Current UPF IP: 10.200.200.103
Previous UPF IP: 10.200.200.102
Next UPF IP: None
panic: runtime error: index out of range [1] with length 1
goroutine 40 …
```
=> Fix NewUEPreConfigPaths when there is only one UPF in path list

consumer/sm_policy.go, go.mod, go.sum, producer/pdu_session.go
Send PDU Session Reject message back.
Note:To compile this PR, you need to merge [Pull Request in the nas library](https://github.com/free5gc/nas/pull/8) and [Pull Request in the openapi library](https://github.com/free5gc/openapi/pull/2).
=> Fix: PDU Session Establishment panic without DNN for subscription

producer/pdu_session.go
encode plmnId as json by openapi.MarshToJsonString
=> fix(smf): plmnId should be encoded as json format in HTTP header

context/datapath.go
Modified to release UpLinkTunnel information.
=> Fix: DeactivateUpLinkTunnel mistakenly released DownLinkTunnel teid.

internal/context/datapath.go
=> Fix typo in log message

internal/context/ue_defaultPath.go
Closes #40
Thanks you @aviweit for the proposed patch
A related forum issue this patch fixes as well: https://forum.free5gc.org/t/issues-with-ueroutinginfo/1214
=> Send all PFCP rules correctly when using ULCL

internal/logger/logger.go
from second to nanosecond. it helps in merging NF logs together and sort their logs.
=> increasing timestamp precison

pkg/factory/factory.go
This reverts commit abec5eee22d00ed563f492357ecf680449aead69.
=> Revert "changed sd to lowercase (#81)"

internal/sbi/consumer/sm_policy.go
=> 	modified:   internal/sbi/consumer/sm_policy.go

internal/sbi/oam/api_get_smf_config.go, internal/sbi/oam/routers.go, internal/sbi/producer/oam.go
OAM service will provide UserPlanInfo from the config file.
=> feat: UserPlanInfo OAM service

.github/workflows/commit-msg-check.yml
This pull request adds CI Action to check whether commit messages follow [Conventional Commit Messages](https://www.conventionalcommits.org/en/v1.0.0/) or not. 
- https://github.com/webiny/action-conventional-commits 
- https://www.conventionalcommits.org/en/v1.0.0/
=> feat: Create commit-msg-check.yml

internal/sbi/processor/pdu_session.go, internal/sbi/processor/pdu_session_test.go
Fix JSON object directly without MIME multipart.
=> fix: error response type

internal/sbi/consumer/chf_service.go
Fix for https://github.com/free5gc/free5gc/issues/587.
=> Add nil check for httpResponse in SendConvergedChargingRequest

internal/sbi/processor/ulcl_procedure.go
- To solve [free5gc issue #599](https://github.com/free5gc/free5gc/issues/599)
=> fix: swap source and destination when createing flowDescription of ULCL paths

internal/context/datapath.go, internal/context/user_plane_information.go, internal/pfcp/message/build.go
- Missed URR creation will caused panic error
=> fix: UPF missing URR error

internal/sbi/processor/pdu_session.go
[https://github.com/free5gc/free5gc/issues/610](https://github.com/free5gc/free5gc/issues/610)
=> fix: pointer Comparison Logic Error

internal/context/sm_context.go
- revert ULCL related path creation.
=> fix: revert ULCL creating default path

internal/context/gsm_build.go, internal/context/sm_context.go
[#617](https://github.com/free5gc/free5gc/issues/617)
=> fix: qos id identical in pdu session establishment accept message error

internal/context/sm_context.go, internal/sbi/processor/ulcl_procedure.go
=> feat: Add session level charging URRs to ULCL created path

internal/context/datapath.go
Please merge  https://github.com/free5gc/gtp5g/pull/138 first.
=> feat: add UE IP Address IE on downlink PDRs
